### ISSUE TITLE
notes.map is not a function at video 65 

### ISSUE THREAD

**Issue by SarikAnwar01** [CodeWithHarry/iNotebook-React#21]
at Notes (Notes.js:16:1)

**Comment by ramshahu** [comment]
check your auth.js file and fetchuser.js file in backend. you might have written auth-token. simple write auth-token instead of token in localStorage.getItem('auth-token') in NoteState.js,login.js,signup.js.,Notes.js and Navbar.js. Also replace the json.authtoken with authToken in Login.js and Signup.js. hope this will help you
